version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: cvscanner-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - cv-network
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 10

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - cv-network

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 10s
      timeout: 5s
      retries: 10

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8890:8890"
    networks:
      - cv-network

  api-gateway:
    build: ./gateway-service
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
    networks:
      - cv-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: ${AUTH_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      SPRING_APPLICATION_NAME: AUTH-SERVICE

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 86400000
    networks:
      - cv-network

  upload-service:
    build: ./upload-service
    container_name: upload-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: ${UPLOAD_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - cv-network

  batch-service:
    build: ./batch-service
    container_name: batch-service
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${BATCH_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_APPLICATION_NAME: BATCH-SERVICE
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

      JWT_SECRET: ${JWT_SECRET}
    networks:
      - cv-network

  parser-service:
    build: ./parser-service
    container_name: parser-service
    ports:
      - "8084:8084"
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: PARSER-SERVICE
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 86400000

    networks:
      - cv-network

  candidate-service:
    build: ./candidate-service
    container_name: candidate-service
    ports:
      - "8085:8085"
    depends_on:
      postgres:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: CANDIDATE-SERVICE
      SPRING_DATASOURCE_URL: ${CANDIDATE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}

      JWT_SECRET: ${JWT_SECRET}
    networks:
      - cv-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8086:8086"
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: NOTIFICATION-SERVICE
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}

      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true

      JWT_SECRET: ${JWT_SECRET}
    networks:
      - cv-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - cv-network

networks:
  cv-network:

volumes:
  pg_data: