server.port=8082
spring.application.name=UPLOAD-SERVICE
file.upload-dir=./uploads/

spring.datasource.url=${UPLOAD_DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# EUREKA
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
jwt.secret=${JWT_SECRET}
springdoc.swagger-ui.use-root-path=true
springdoc.api-docs.enabled=true


