
spring.application.name=PARSER-SERVICE
server.port=8084

gemini.api.key=AIzaSyCX-ldqLbZ7QWn_fDXF_yOhNvpwW4BNsw4
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
jwt.secret=${JWT_SECRET}
springdoc.swagger-ui.use-root-path=true
springdoc.api-docs.enabled=true