spring.application.name=batch-service
server.port=8083

spring.batch.job.enabled=false
spring.main.allow-bean-definition-overriding=true

# DATABASE
spring.datasource.url=${BATCH_DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 🔥 FIX
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# retry fix
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=30000

# BATCH
spring.batch.jdbc.initialize-schema=always

# EUREKA
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# FILE PATH
file.upload-dir=/app/uploads
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
jwt.secret=${JWT_SECRET}
springdoc.swagger-ui.use-root-path=true
springdoc.api-docs.enabled=true